# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/said/Dev/CmakeLearn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/said/Dev/CmakeLearn

# Include any dependencies generated for this target.
include AdderLib/CMakeFiles/AdderLib.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include AdderLib/CMakeFiles/AdderLib.dir/compiler_depend.make

# Include the progress variables for this target.
include AdderLib/CMakeFiles/AdderLib.dir/progress.make

# Include the compile flags for this target's objects.
include AdderLib/CMakeFiles/AdderLib.dir/flags.make

AdderLib/CMakeFiles/AdderLib.dir/adder.cpp.o: AdderLib/CMakeFiles/AdderLib.dir/flags.make
AdderLib/CMakeFiles/AdderLib.dir/adder.cpp.o: AdderLib/adder.cpp
AdderLib/CMakeFiles/AdderLib.dir/adder.cpp.o: AdderLib/CMakeFiles/AdderLib.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/said/Dev/CmakeLearn/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object AdderLib/CMakeFiles/AdderLib.dir/adder.cpp.o"
	cd /Users/said/Dev/CmakeLearn/AdderLib && /Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT AdderLib/CMakeFiles/AdderLib.dir/adder.cpp.o -MF CMakeFiles/AdderLib.dir/adder.cpp.o.d -o CMakeFiles/AdderLib.dir/adder.cpp.o -c /Users/said/Dev/CmakeLearn/AdderLib/adder.cpp

AdderLib/CMakeFiles/AdderLib.dir/adder.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/AdderLib.dir/adder.cpp.i"
	cd /Users/said/Dev/CmakeLearn/AdderLib && /Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/said/Dev/CmakeLearn/AdderLib/adder.cpp > CMakeFiles/AdderLib.dir/adder.cpp.i

AdderLib/CMakeFiles/AdderLib.dir/adder.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/AdderLib.dir/adder.cpp.s"
	cd /Users/said/Dev/CmakeLearn/AdderLib && /Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/said/Dev/CmakeLearn/AdderLib/adder.cpp -o CMakeFiles/AdderLib.dir/adder.cpp.s

# Object files for target AdderLib
AdderLib_OBJECTS = \
"CMakeFiles/AdderLib.dir/adder.cpp.o"

# External object files for target AdderLib
AdderLib_EXTERNAL_OBJECTS =

AdderLib/libAdderLib.a: AdderLib/CMakeFiles/AdderLib.dir/adder.cpp.o
AdderLib/libAdderLib.a: AdderLib/CMakeFiles/AdderLib.dir/build.make
AdderLib/libAdderLib.a: AdderLib/CMakeFiles/AdderLib.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/Users/said/Dev/CmakeLearn/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking CXX static library libAdderLib.a"
	cd /Users/said/Dev/CmakeLearn/AdderLib && $(CMAKE_COMMAND) -P CMakeFiles/AdderLib.dir/cmake_clean_target.cmake
	cd /Users/said/Dev/CmakeLearn/AdderLib && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/AdderLib.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
AdderLib/CMakeFiles/AdderLib.dir/build: AdderLib/libAdderLib.a
.PHONY : AdderLib/CMakeFiles/AdderLib.dir/build

AdderLib/CMakeFiles/AdderLib.dir/clean:
	cd /Users/said/Dev/CmakeLearn/AdderLib && $(CMAKE_COMMAND) -P CMakeFiles/AdderLib.dir/cmake_clean.cmake
.PHONY : AdderLib/CMakeFiles/AdderLib.dir/clean

AdderLib/CMakeFiles/AdderLib.dir/depend:
	cd /Users/said/Dev/CmakeLearn && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /Users/said/Dev/CmakeLearn /Users/said/Dev/CmakeLearn/AdderLib /Users/said/Dev/CmakeLearn /Users/said/Dev/CmakeLearn/AdderLib /Users/said/Dev/CmakeLearn/AdderLib/CMakeFiles/AdderLib.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : AdderLib/CMakeFiles/AdderLib.dir/depend

